# Generated by Django 4.2.4 on 2023-08-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cliente_cpf"),
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="cliente",
        ),
        migrations.AddField(
            model_name="venda",
            name="cliente",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.cliente",
            ),
            preserve_default=False,
        ),
    ]
