# Generated by Django 4.2.4 on 2023-08-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cliente_cpf"),
        ("produtos", "0001_initial"),
        ("vendas", "0002_remove_venda_cliente_venda_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="produtos.produto"
            ),
        ),
    ]
