# Generated by Django 4.2.4 on 2023-08-01 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enderecos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.TextField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                (
                    "endereco",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enderecos.endereco",
                    ),
                ),
            ],
        ),
    ]
