# Generated by Django 4.2.4 on 2023-08-01 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cidade", models.TextField(max_length=100)),
                ("estado", models.TextField(max_length=100)),
                ("uf", models.TextField(max_length=2)),
                ("rua", models.TextField(max_length=100)),
                ("numero", models.PositiveIntegerField(max_length=100)),
            ],
        ),
    ]
