# Generated by Django 4.2.4 on 2023-08-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endereco",
            name="estado",
        ),
        migrations.AlterField(
            model_name="endereco",
            name="numero",
            field=models.PositiveIntegerField(),
        ),
    ]
